version: "3.9"
services:
  bot:
    build: .
    volumes:
    - "./logs:/bot/logs"
    - "./config:/bot/config"
    environment:
      PYTHONUNBUFFERED: 1
      SERVER_PORT: ${SERVER_PORT}
      SERVER_NAME: ${SERVER_NAME}
    ports:
      - ${SERVER_PORT}:8080