version: "3.9"
services:
  bot:
    build: .
    volumes:
    - "./logs:/bot/logs"
    - "./config:/bot/config"
    - "./minecraft_server:/bot/servers/smp"
    - "./minecraft_server_two:/bot/servers/cmp"
    environment:
      PYTHONUNBUFFERED: 1
      SERVER_PORT: ${SERVER_PORT}
      SERVER_NAME: ${SERVER_NAME}
    ports:
      - ${SERVER_PORT}:8080
  mc:
    image: itzg/minecraft-server
    ports:
    - 25565:25565
    - 25570:25570
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: 1.16.3
      ENABLE_QUERY: "yes"
    volumes:
    - "./minecraft_server:/data"
    depends_on:
      - mongo
#  mc-two:
#    image: itzg/minecraft-server
#    ports:
#      - 25566:25566
#    environment:
#      EULA: "TRUE"
#      TYPE: "FABRIC"
#      VERSION: 1.16.3
#      RCON_PORT: 25576
#      ENABLE_QUERY: "yes"
#    volumes:
#      - "./minecraft_server_two:/data"
#    depends_on:
#      - mongo
  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    logging:
      driver: "none"
  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
    - 8081:8081
    depends_on:
      - mongo

volumes:
  mongo_data: