version: "3.9"
services:
  bot:
    build: .
    volumes:
    - "./logs:/bot/logs"
    - "./config:/bot/config"
    environment:
      PYTHONUNBUFFERED: 1
      SERVER_PORT: ${SERVER_PORT}
      SERVER_NAME: ${SERVER_NAME}
    ports:
      - ${SERVER_PORT}:8080
  mongo:
    image: mongo
    volumes:
    - "./database:/data/db"
    ports:
    - 27017:27017
    logging:
      driver: "none"