version: "3.9"
services:
  bot:
    build: .
    volumes:
    - "./logs:/bot/logs"
    - "./config:/bot/config"
    - "C:/Users/nirjh/Desktop/LiteTech/Logos:/bot/servers/smp"
    environment:
      PYTHONUNBUFFERED: 1