version: "3.9"
services:
  bot:
    build: .
    volumes:
    - "./logs:/bot/logs"
    - "./config:/bot/config"
    - "./plugins:/bot/plugins"
    environment:
      PYTHONUNBUFFERED: 1
    env_file:
      - .env
    ports:
    - ${SERVER_PORT}:${SERVER_PORT}
  mongo:
    image: mongo
    volumes:
    - mongo_data:/data/db
    ports:
    - 27017:27017
    logging:
      driver: none
  mongo-express:
    image: mongo-express:0.54.0
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'false'
      ME_CONFIG_MONGODB_AUTH_DATABASE: bot
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_PASSWORD}
    ports:
      - 8081:8081
    depends_on:
      - mongo
    logging:
      driver: none
volumes:
  mongo_data: